apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: pod-mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
        ports:
        - containerPort: 3306
